version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ozon"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

